# https://docs.aws.amazon.com/lambda/latest/dg/images-create.html
FROM python:buster as build-image

ENV APP_DIR /var/task
ENV PATH /var/task/bin:$PATH
ENV PYTHONPATH /var/task/src:/var/task/lib

RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR
RUN mkdir lib

# Install aws-lambda-cpp build dependencies
RUN apt-get update && \
  apt-get install -y \
  g++ \
  make \
  cmake \
  unzip \
  libcurl4-openssl-dev

# Copy function code
COPY src/* .
COPY bin ./bin
COPY requirements.txt .
COPY entry_script.sh .

RUN apt-get update

# set the timezone
# https://stackoverflow.com/a/44333806
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
RUN apt-get install -y tzdata
RUN dpkg-reconfigure --frontend noninteractive tzdata
# install deps for selenium
# https://stackoverflow.com/a/49710327
RUN apt-get install -y libglib2.0-0 \
    libnss3 \
    libgconf-2-4 \
    libfontconfig1 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1

# https://unix.stackexchange.com/a/590412
RUN wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_86.0.4240.75-1_amd64.deb \
  && apt install -y /tmp/chrome.deb \
  && rm /tmp/chrome.deb
# RUN apt-get install -y ./google-chrome-stable_current_amd64.deb

# https://askubuntu.com/a/510186
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# RUN echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
# RUN apt-get update

# Install the runtime interface client
RUN pip install -r requirements.txt -t lib

RUN useradd -u 8877 docker-user
USER docker-user

ENTRYPOINT ["/var/task/entry_script.sh"]
CMD ["purchase.lambda_handler"]